### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by thenewtonium**
Added dark mode to the site (as I suggested in #227 ), including a theme switcher at the foot of every page.
The giscus widget theme is also set to match the site theme, updating whenever the site theme is changed.
Theme is based initially off of the user's browser dark mode settings, then subsequently localStorage is used to store theme settings.
Switching between tabs/windows also triggers loading of theme settings from localStorage, so if you change theme in one tab it will carry across without reloading.

Colours are all specified in `/src/css/variable.css`; I literally just inverted all the light mode colours to get the dark mode theme, except for the colour of `<hr>` because the colour of that was defined weirdly. In particular, links (outside giscus of course) show up as orange on dark mode. If you don't like my lazy dark mode colour scheme, I've made it easy to change it...

Images are inverted to blend into dark mode; this should be fine as they are all black and white. I've also added a `nofilter` css class that can be added to an image to stop it being inverted.

### CODE REVIEW

**Comment by AustenLamacraft** [comment]
This is amazing! Do you think it would be possible to put the control in the header rather than the footer? And perhaps a slider, [like this](https://codepen.io/cortez/pen/jOrNGGQ) maybe?

**Comment by thenewtonium** [comment]
Sure, the switcher I made for this PR is essentially a placeholder (I was envisaging eventually having little sun/moon buttons to change theme). A slider would be cool, and it should be fairly easy to integrate that slider code into my theme-switching code.
The reason I put my switcher in the footer though is there doesn't really seem to be a good space for it to go in the header?

**Comment by AustenLamacraft** [comment]
I guess the natural place might be top right like this...

image

**Comment by thenewtonium** [comment]
But on desktop that puts it between title and navbar.

**Comment by AustenLamacraft** [comment]
Perhaps a little moon / sun in the navbar then?

**Comment by AustenLamacraft** [comment]
By the way this isn't building on Netlify because of memory issues (nothing to do with the PR, I think). If necessary I can build it locally

**Comment by thenewtonium** [comment]
Maybe a little rounder? What I liked about the old moon icon is that it transitions nicely, since both it and the sun icon are round.

Like this perhaps:

**Pull request merged**
