### PR TITLE
Add course / year headings on year / course pages resp.

### PR DESCRIPTION
**Pull request by thenewtonium**
And also navigation at the top of page to jump to a particular section.

### CODE REVIEW

**Comment by AustenLamacraft** [comment]
This is fantastic! One thought: would it make sense to reverse the year order on the subject listing page (starting with most recent)?

**Comment by Trixelian** [comment]
> This is fantastic! One thought: would it make sense to reverse the year order on the subject listing page (starting with most recent)?

Personally I'd prefer most recent ordering, as I'm more likely to do a 2017 question than a 2005 question - is there a possibility of adding a sort direction button?

**Comment by thenewtonium** [comment]
I agree also that reverse chronological order is more useful.

---

On a *somewhat* related note: someone on the discord recently was saying that he wished you could filter by paper, since scrolling through a year or course page spoils questions.

Thoughts about wrapping the body of each question in `<details>` on these pages? (And adding a button to expand them all for people who want to browse or something.)

**Comment by AustenLamacraft** [comment]
> > This is fantastic! One thought: would it make sense to reverse the year order on the subject listing page (starting with most recent)?
> 
> Personally I'd prefer most recent ordering, as I'm more likely to do a 2017 question than a 2005 question - is there a possibility of adding a sort direction button?

I don't know if it needs a button. If we think most recent is the best, let's go with that.

**Comment by AustenLamacraft** [comment]
> On a _somewhat_ related note: someone on the discord recently was saying that he wished you could filter by paper, since scrolling through a year or course page spoils questions.
> 
> Thoughts about wrapping the body of each question in `<details>` on these pages? (And adding a button to expand them all for people who want to browse or something.)

Wow, that would never occur to me! Is the point that people want to practice a whole paper, and don’t want to see any of another paper? I guess one could add a filter to select all questions from a given paper.

**Comment by thenewtonium** [comment]
That and more broadly some people do like to "save" a paper (usually most recent) for doing as a mock, and so don't want to spoil the questions. Personally I don't really do this but I think that's the idea 🤷

**Comment by AustenLamacraft** [comment]
Looks great! I think that `Reverse year order` isn't really necessary on the course pages, though. If you think it really adds something let's keep it, but I'd be happy with just the newest to oldest order.

[This is just a thought, I'm not suggesting you do more work] I guess an alternative to having papers for each question would be to dynamically filter the questions for a year to display only those from a particular paper [like this](https://www.w3schools.com/howto/howto_js_filter_elements.asp)

**Pull request merged**
